name: Resource Deployment PR

on: 
 pull_request:
   types: [opened, synchronize, reopened, edited]
   paths:
    - ".github/workflows/deployment-pr.yml"
    - "Deployment/**"

permissions:
 id-token: write
 contents: read

jobs:
 Deployment:
  runs-on: ubuntu-latest
  steps:
   - name: PR deployment
     uses: NizamORG/terraform-reusable/.github/workflows/terraform-pr.yml@main
     secrets: inherit
     with:
      subscription-id: ${{vars.SUBSCRIPTION_ID}}
      workingdirectory: ./Deployment