name: Resource Deployment PR

on: 
 pull_request:
   types: [opened, synchronize, reopened, edited]
   paths:
    - ".github/workflows/deployment-pr.yml"
    - "Deployment/**"

jobs:
 Deployment:
  name: Terraform Plan PR
  uses: NizamORG/Terraform-reusable/.github/workflows/terraform-pr.yml@main
  secrets: inherit
  with:
   subscription-id: ${{vars.SUBSCRIPTION_ID}}
   workingdirectory: ./Deployment